/* eslint-disable @next/next/no-img-element */
// Progressive-enhancement <picture> for the photo assets. For each JPG we ship
// AVIF + WebP siblings (generated by scripts/encode at build time) and a small
// "-sm" variant for phones. Browsers pick the smallest format they support; the
// original <img src="…jpg"> stays as the universal fallback, so behaviour can
// only ever match or improve — never regress. The big lightbox photo keeps the
// full-resolution source, so on-screen sharpness is untouched.
//
// className defaults to "rsp" (globals: `picture.rsp{display:contents}`) so the
// wrapper is layout-transparent and the inner <img> sizes exactly as before.
// Pass an explicit className (e.g. "") where the <picture> needs its own box
// (pricelist prints use `.pl-print picture{aspect-ratio}`).

const swap = (src: string, ext: string) => src.replace(/\.jpg$/i, ext);
const small = (src: string) => swap(src, "-sm.jpg");

function variants(src: string) {
  const sm = small(src);
  return {
    jpg: src,
    webp: swap(src, ".webp"),
    avif: swap(src, ".avif"),
    smJpg: sm,
    smWebp: swap(sm, ".webp"),
    smAvif: swap(sm, ".avif"),
  };
}

type PicProps = {
  src: string;
  alt: string;
  className?: string;
  id?: string;
  imgClassName?: string;
  loading?: "lazy" | "eager";
  draggable?: boolean;
};

// Responsive photo: phones (<=768px) get the small variants, larger screens the
// full ones; each tier offers avif → webp → jpg.
export default function Pic({
  src,
  alt,
  className = "rsp",
  id,
  imgClassName,
  loading,
  draggable,
}: PicProps) {
  const v = variants(src);
  return (
    <picture className={className}>
      <source media="(max-width: 768px)" type="image/avif" srcSet={v.smAvif} />
      <source media="(max-width: 768px)" type="image/webp" srcSet={v.smWebp} />
      <source media="(max-width: 768px)" srcSet={v.smJpg} />
      <source type="image/avif" srcSet={v.avif} />
      <source type="image/webp" srcSet={v.webp} />
      <img
        src={v.jpg}
        alt={alt}
        id={id}
        className={imgClassName}
        loading={loading}
        decoding="async"
        draggable={draggable}
      />
    </picture>
  );
}

// Thumbnail (lightbox filmstrip): always the small variant, avif → webp → jpg.
export function PicThumb({ src, alt = "" }: { src: string; alt?: string }) {
  const v = variants(src);
  return (
    <picture className="rsp">
      <source type="image/avif" srcSet={v.smAvif} />
      <source type="image/webp" srcSet={v.smWebp} />
      <img src={v.smJpg} alt={alt} loading="lazy" decoding="async" />
    </picture>
  );
}
